#ENTRADAS DE DATOS
#Obtener los dos datos

numero1 = 10
numero2 = 2






# PROCESOS (Operaciones o Cálculos Matemáticos y Lógicos)
# Operaciones de los dos numeros

suma = numero1 + numero2
resta = numero1 - numero2
multiplicacion = numero1 * numero2
division = numero1 / numero2
potencia1 = numero1 ** numero2
potencia2 = pow(numero1, numero2)
cuadrado1 = numero1 ** 2
cubo1 = numero1 ** 3
cuadrado2 = pow(numero1, 2) #numero1 **2
cubo2 = pow(numero1, 3) #Numero1 **3
raiz = pow(numero1, 2)







#SALIDAS DE DATOS 
#Resultado de las operaciones 
print("La suma es igual a",suma)
print("La suma = " + str(suma)) #Concatenacion (union de textos)
print(f"La suma = {suma}")
print("La resta es igual a", resta)
print("La resta =" + str(resta))
print(f"La resta = {resta}")
print("La multiplicacion es igual a", multiplicacion)
print("La multiplicacion =" + str(multiplicacion))
print(f"La multiplicacion = {multiplicacion}")
print("La division es igual a", division)
print("La division = " + str(division))
print(f"La division = {division}")
print("La potencia1 es igual a", potencia1)
print("La potencia1 = " + str(potencia1))
print(f"La potencia = {potencia1}")
print("La potencia2 es igual a", potencia2)
print("potencia2 = " + str(potencia2))
print(f"La potencia2 = {potencia2}")
print("El cuadrado1 es igual a", cuadrado1)
print("El cuadrado1 = " + str(cuadrado1))
print(f"El cuadrado1 = {cuadrado1}")
print("El cubo1 es igual a", cubo1)
print("La cubo1 = " + str(cubo1))
print(f"El cubo1 = {cubo1}")
print("El cuadrado2 es igual a", cuadrado2)
print("La cuadrado2 = " + str(cuadrado2))
print(f"El cuadrado2 = {cuadrado2}")
print("El cubo2 es igual a", cubo2)
print("La cubo2 = " + str(cubo2))
print(f"El cubo2 = {cubo2}")
print("La raiz es igual a", raiz)
print("La raiz = " + str(raiz))
print(f"La raiz = {raiz}")
